project_id = "fmtikdkgfmumbqjndbss"

[functions.setup-first-admin]
verify_jwt = true

[functions.analyze-titles]
verify_jwt = false

[functions.batch-niche-search]
verify_jwt = false

[functions.generate-scene-prompts-v2]
verify_jwt = false

[functions.model-thumbnail]
verify_jwt = true

[functions.analyze-thumbnail-streaming]
verify_jwt = false

[functions.generate-thumbnail-variations]
verify_jwt = false